name: ROM build status

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: installing dependencies
      run: sudo apt install build-essential binutils-arm-none-eabi git libpng-dev
    - name: clone agbcc
      run: git clone https://github.com/pret/agbcc ~/agbcc
    - name: install agbcc
      run: cd ~/agbcc; ./build.sh; ./install.sh $GITHUB_WORKSPACE
    - name: make
      run: make -j$(nproc); make leafgreen
    - name: make _rev files
      run: make firered_rev1; make leafgreen_rev1
    - name: Upload ROM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rom-builds
        path: pokeiceturquoise.gba; pokemindpink.gba; pokeiceturquoise_rev1.gba; pokemindpink_rev1.gba